/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package prn315.guia11.ejemplosbd.registrarusuario;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author rchicas
 */
public class MantenimientoProductos extends javax.swing.JFrame {

    public ProductoTableModel productoTModel = new ProductoTableModel();
    private Connection conexion;
    private boolean guardar = true;
    private Producto productoActual;

    /**
     * Creates new form DatosPersonales
     */
    public MantenimientoProductos() {
        initComponents();

        inicializarColumnas();
        conectar();
        consultaInicial();
    }

    private void inicializarColumnas() {
        TableColumnModel tColumnModel = new DefaultTableColumnModel();

        for (int i = 0; i < 4; i++) {
            TableColumn col = new TableColumn(i);

            switch (i) {
                case 0:
                    col.setHeaderValue("Código");
                    break;
                case 1:
                    col.setHeaderValue("Nombre");
                    break;
                case 2:
                    col.setHeaderValue("Existencia");
                    break;
                case 3:
                    col.setHeaderValue("Precio");
            }

            tColumnModel.addColumn(col);
        }

        tablaProductos.setColumnModel(tColumnModel);
    }

    private void conectar() {
        try {
            conexion = DriverManager.getConnection("jdbc:postgresql://192.168.90.57:5432/prn315", "prn315", "prn315");
            //conexion = DriverManager.getConnection("jdbc:postgresql://localhost:5432/prn315", "prn315", "prn315");

        } catch (SQLException ex) {
            Logger.getLogger(MantenimientoProductos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void consultaInicial() {
        try {
            String sentenciaSql = "SELECT * FROM producto";
            Statement statement = this.conexion.createStatement();

            ResultSet resultado = statement.executeQuery(sentenciaSql);

            while (resultado.next()) {
                Producto producto = new Producto();

                producto.codigo = resultado.getString("codigo");
                producto.nombre = resultado.getString("nombre");
                producto.cantidadExistencia = resultado.getDouble("cantidad_existencia");
                producto.precioUnitario = resultado.getDouble("precio_unitario");

                this.productoTModel.productos.add(producto);
            }

            tablaProductos.repaint();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al recuperar los productos de la base de datos");
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollTablaProd = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lCodigo = new javax.swing.JLabel();
        lNombre = new javax.swing.JLabel();
        lCantidadExist = new javax.swing.JLabel();
        lPrecioUnit = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        scrollNombreProd = new javax.swing.JScrollPane();
        txtNombre = new javax.swing.JTextArea();
        txtCant = new javax.swing.JFormattedTextField();
        txtPrecio = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        lBusqCod = new javax.swing.JLabel();
        lBusqNombre = new javax.swing.JLabel();
        txtBusqCodigo = new javax.swing.JTextField();
        txtBusqNombre = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        tablaProductos.setModel(productoTModel);
        tablaProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProductosMouseClicked(evt);
            }
        });
        scrollTablaProd.setViewportView(tablaProductos);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Mantenimiento"));

        lCodigo.setText("Código:");

        lNombre.setText("Nombre:");

        lCantidadExist.setText("Cantidad en existencia:");

        lPrecioUnit.setText("Precio unitario:");

        txtCodigo.setColumns(16);

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        txtNombre.setColumns(16);
        txtNombre.setRows(5);
        scrollNombreProd.setViewportView(txtNombre);

        txtCant.setColumns(8);
        txtCant.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));

        txtPrecio.setColumns(8);
        txtPrecio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lPrecioUnit, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lCantidadExist, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lCodigo, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scrollNombreProd, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnGuardar)
                                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(btnNuevo)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCodigo)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(scrollNombreProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lCantidadExist))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lPrecioUnit)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnNuevo))
                .addGap(14, 14, 14))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Criterios de búsqueda"));

        lBusqCod.setText("Código");

        lBusqNombre.setText("Nombre:");

        txtBusqCodigo.setColumns(16);

        txtBusqNombre.setColumns(16);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lBusqCod, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lBusqNombre, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBusqNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBusqCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBuscar)
                .addGap(81, 81, 81))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lBusqCod)
                    .addComponent(txtBusqCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtBusqNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lBusqNombre)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnEliminar.setText("Eliminar seleccionados");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(scrollTablaProd, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnEliminar)
                        .addGap(53, 53, 53))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollTablaProd, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEliminar)
                .addGap(17, 17, 17)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            // TODO add your handling code here:

            if (guardar) {
                Producto producto = new Producto();

                producto.codigo = txtCodigo.getText();
                producto.nombre = txtNombre.getText();
                producto.cantidadExistencia = Double.parseDouble(txtCant.getText());
                producto.precioUnitario = Double.parseDouble(txtPrecio.getText());

                String sentenciaSql = "INSERT INTO producto(codigo, nombre, cantidad_existencia, precio_unitario) VALUES "
                        + "(?,?,?,?)";

                PreparedStatement preparedStatement = conexion.prepareStatement(sentenciaSql);
                preparedStatement.setString(1, producto.codigo);
                preparedStatement.setString(2, producto.nombre);
                preparedStatement.setDouble(3, producto.cantidadExistencia);
                preparedStatement.setDouble(4, producto.precioUnitario);

                preparedStatement.execute();

                productoTModel.productos.add(producto);


            } else {
                String sentenciaSql = "UPDATE producto SET nombre = ?, cantidad_existencia = ?, precio_unitario = ? WHERE codigo = ?";

                PreparedStatement preparedStatement = conexion.prepareStatement(sentenciaSql);
                preparedStatement.setString(1, txtNombre.getText());
                preparedStatement.setDouble(2, Double.valueOf(txtCant.getText()));
                preparedStatement.setDouble(3, Double.parseDouble(txtPrecio.getText()));
                preparedStatement.setString(4, txtCodigo.getText());

                preparedStatement.executeUpdate();

                productoActual.cantidadExistencia = Double.parseDouble(txtCant.getText());
                productoActual.codigo = txtCodigo.getText();
                productoActual.nombre = txtNombre.getText();
                productoActual.precioUnitario = Double.parseDouble(txtPrecio.getText());
            }

            scrollTablaProd.setViewportView(tablaProductos);
            tablaProductos.repaint();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al guardar el producto");
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:

        txtCodigo.setText("");
        guardar = true;
        productoActual = null;
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void tablaProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProductosMouseClicked
        // TODO add your handling code here:
        int clics = evt.getClickCount();
        int row = tablaProductos.rowAtPoint(evt.getPoint());

        if (clics == 2) {
            Producto p = productoTModel.productos.get(row);
            productoActual = p;

            txtCodigo.setText(p.codigo);
            txtNombre.setText(p.nombre);
            txtCant.setText(String.valueOf(p.cantidadExistencia.doubleValue()));
            txtPrecio.setText(String.valueOf(p.precioUnitario.doubleValue()));

            guardar = false;
        }
    }//GEN-LAST:event_tablaProductosMouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:

        productoTModel.productos.clear();

        try {
            PreparedStatement statement = null;

            String codigo = txtBusqCodigo.getText();
            String nombre = txtBusqNombre.getText();

            String sentenciaSql = "SELECT * FROM producto ";

            if (!codigo.isEmpty()) {
                if (!nombre.isEmpty()) {
                    sentenciaSql += "WHERE codigo ILIKE ? OR nombre ILIKE ?";
                    statement = this.conexion.prepareStatement(sentenciaSql);
                    statement.setString(1, codigo + "%");
                    statement.setString(2, "%" + nombre + "%");
                } else {
                    sentenciaSql += "WHERE codigo ILIKE ? ";
                    statement = this.conexion.prepareStatement(sentenciaSql);
                    statement.setString(1, codigo + "%");
                }
            } else {
                if (!nombre.isEmpty()) {
                    sentenciaSql += "WHERE nombre ILIKE ?";
                    statement = this.conexion.prepareStatement(sentenciaSql);
                    statement.setString(1, "%" + nombre + "%");
                } else {
                    statement = this.conexion.prepareStatement(sentenciaSql);
                }
            }

            ResultSet resultado = statement.executeQuery();

            while (resultado.next()) {
                Producto producto = new Producto();

                producto.codigo = resultado.getString("codigo");
                producto.nombre = resultado.getString("nombre");
                producto.cantidadExistencia = resultado.getDouble("cantidad_existencia");
                producto.precioUnitario = resultado.getDouble("precio_unitario");

                productoTModel.productos.add(producto);
            }

            scrollTablaProd.setViewportView(tablaProductos);
            tablaProductos.repaint();


        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al recuperar los productos de la base de datos");
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:

        //Indices de las filas seleccionadas
        int[] indices = tablaProductos.getSelectedRows();
        List<Producto> aEliminar = new ArrayList<Producto>();


        for (int i : indices) {
            Producto producto = productoTModel.productos.get(i);

            String sentenciaSql = "DELETE FROM producto WHERE codigo = ?";

            aEliminar.add(producto);

            try {
                PreparedStatement prepStat = conexion.prepareStatement(sentenciaSql);
                prepStat.setString(1, producto.codigo);

                prepStat.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(MantenimientoProductos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        productoTModel.productos.removeAll(aEliminar);
        scrollTablaProd.setViewportView(tablaProductos);
        tablaProductos.repaint();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:

            conexion.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error al cerrar la conexión a la base de datos");
        }
        JOptionPane.showMessageDialog(this, "La conexión a la base de datos ha sido cerrada");
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MantenimientoProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MantenimientoProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MantenimientoProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MantenimientoProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MantenimientoProductos().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lBusqCod;
    private javax.swing.JLabel lBusqNombre;
    private javax.swing.JLabel lCantidadExist;
    private javax.swing.JLabel lCodigo;
    private javax.swing.JLabel lNombre;
    private javax.swing.JLabel lPrecioUnit;
    private javax.swing.JScrollPane scrollNombreProd;
    private javax.swing.JScrollPane scrollTablaProd;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JTextField txtBusqCodigo;
    private javax.swing.JTextField txtBusqNombre;
    private javax.swing.JFormattedTextField txtCant;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextArea txtNombre;
    private javax.swing.JFormattedTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
